services:
  django_test:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_tenant_options
    container_name: django_test
    volumes:
      - ./example_project:/app/example_project
      - ./src:/app/src
    env_file:
      - ./compose/django/.django
    ports:
      - "8111:8111"
    command: /start
