"""Pure code-generation helpers for the startoptions management command.

Every function in this module is free of side effects except for the explicit
filesystem helper append_code_to_file. The render_* functions return source
strings so they can be unit-tested without touching the database or disk.
"""

import logging
import os


logger = logging.getLogger("django_tenant_options")


def validate_name(name):
    """Validate and return a PascalCase model base name.

    Args:
        name: The proposed model base name, for example "Priority".

    Returns:
        The validated name, unchanged.

    Raises:
        ValueError: If name is empty, not a valid Python identifier, or does
            not start with an uppercase letter.
    """
    if not name:
        raise ValueError("Name must not be empty.")
    if not name.isidentifier():
        raise ValueError(f"Name '{name}' is not a valid Python identifier.")
    if not name[0].isupper():
        raise ValueError(f"Name '{name}' must start with an uppercase letter (PascalCase).")
    return name


MODELS_IMPORTS = """from django_tenant_options.choices import OptionType
from django_tenant_options.models import AbstractOption
from django_tenant_options.models import AbstractSelection
"""


def render_models_code(name, app_label, tenant_model):
    """Render the source for a concrete Option and Selection model pair.

    Args:
        name: The PascalCase model base name, for example "Priority".
        app_label: The Django app label the models live in, for example "example".
        tenant_model: The dotted tenant model path, for example "example.Tenant".

    Returns:
        A string of Python source defining {name}Option and {name}Selection.
        The string does not include the import lines; those are returned by
        render_models_imports so the command can add them only when missing.
    """
    return (
        f"class {name}Option(AbstractOption):\n"
        f'    """Concrete Option model for {name}, generated by startoptions."""\n'
        "\n"
        f'    tenant_model = "{tenant_model}"\n'
        f'    selection_model = "{app_label}.{name}Selection"\n'
        "    # Define your default options here, for example:\n"
        '    #     "High": {"option_type": OptionType.MANDATORY},\n'
        '    #     "Low": {"option_type": OptionType.OPTIONAL},\n'
        "    default_options = {}\n"
        "\n"
        "    class Meta(AbstractOption.Meta):\n"
        f'        """Meta options for {name}Option."""\n'
        "\n"
        f'        verbose_name = "{name} Option"\n'
        f'        verbose_name_plural = "{name} Options"\n'
        "\n"
        "\n"
        f"class {name}Selection(AbstractSelection):\n"
        f'    """Concrete Selection model for {name}, generated by startoptions."""\n'
        "\n"
        f'    tenant_model = "{tenant_model}"\n'
        f'    option_model = "{app_label}.{name}Option"\n'
        "\n"
        "    class Meta(AbstractSelection.Meta):\n"
        f'        """Meta options for {name}Selection."""\n'
        "\n"
        f'        verbose_name = "{name} Selection"\n'
        f'        verbose_name_plural = "{name} Selections"\n'
    )


def render_models_imports():
    """Return the import lines required by render_models_code output."""
    return MODELS_IMPORTS


ADMIN_IMPORTS = """from django.contrib import admin

from django_tenant_options.admin import BaseOptionsAdmin
from django_tenant_options.admin import BaseSelectionsAdmin
"""


def render_admin_code(name):
    """Render admin registration source for the generated model pair.

    Args:
        name: The PascalCase model base name, for example "Priority".

    Returns:
        A string of Python source registering {name}Option and {name}Selection.
        Import lines are returned separately by render_admin_imports.
    """
    return (
        f"@admin.register({name}Option)\n"
        f"class {name}OptionAdmin(BaseOptionsAdmin):\n"
        f'    """Admin for {name}Option, generated by startoptions."""\n'
        "\n"
        "\n"
        f"@admin.register({name}Selection)\n"
        f"class {name}SelectionAdmin(BaseSelectionsAdmin):\n"
        f'    """Admin for {name}Selection, generated by startoptions."""\n'
    )


def render_admin_imports(app_label, name):
    """Return the import lines required by render_admin_code output.

    Args:
        app_label: The Django app label, for example "example".
        name: The PascalCase model base name, for example "Priority".

    Returns:
        The admin import block, including importing the generated models from
        the app's models module.
    """
    return (
        ADMIN_IMPORTS + f"from {app_label}.models import {name}Option\nfrom {app_label}.models import {name}Selection\n"
    )


FORMS_IMPORTS = """from django import forms

from django_tenant_options.forms import OptionCreateFormMixin
from django_tenant_options.forms import SelectionsForm
"""


def render_forms_code(name):
    """Render form source for the generated model pair.

    Args:
        name: The PascalCase model base name, for example "Priority".

    Returns:
        A string of Python source defining a SelectionsForm subclass and an
        OptionCreateForm. Import lines are returned separately by
        render_forms_imports.
    """
    return (
        f"class {name}SelectionsForm(SelectionsForm):\n"
        f'    """Selections form for {name}, generated by startoptions."""\n'
        "\n"
        "    class Meta:\n"
        f'        """Meta options for {name}SelectionsForm."""\n'
        "\n"
        f"        model = {name}Selection\n"
        "\n"
        "\n"
        f"class {name}OptionCreateForm(OptionCreateFormMixin, forms.ModelForm):\n"
        f'    """Create form for custom {name} options, generated by startoptions."""\n'
        "\n"
        "    class Meta:\n"
        f'        """Meta options for {name}OptionCreateForm."""\n'
        "\n"
        f"        model = {name}Option\n"
        '        fields = "__all__"\n'
    )


def render_forms_imports(app_label, name):
    """Return the import lines required by render_forms_code output.

    Args:
        app_label: The Django app label, for example "example".
        name: The PascalCase model base name, for example "Priority".

    Returns:
        The forms import block, including importing the generated models from
        the app's models module.
    """
    return (
        FORMS_IMPORTS + f"from {app_label}.models import {name}Option\nfrom {app_label}.models import {name}Selection\n"
    )


def append_code_to_file(file_path, imports, body):
    """Append generated import lines and a code body to a Python file.

    Creates the file if it does not exist. Each import line in imports is only
    added if it is not already present somewhere in the existing file content,
    so re-running the command does not duplicate imports.

    Args:
        file_path: Absolute path to the target .py file.
        imports: A string of import lines (each ending in a newline) to ensure
            are present near the top of the file.
        body: The code body to append at the end of the file.
    """
    existing = ""
    if os.path.exists(file_path):
        with open(file_path, encoding="utf-8") as handle:
            existing = handle.read()

    existing_lines = existing.splitlines()
    missing_imports = []
    for line in imports.splitlines():
        if line.strip() and line not in existing_lines:
            missing_imports.append(line)

    pieces = []
    if not existing:
        pieces.append('"""Generated by django-tenant-options startoptions."""\n')
    if missing_imports:
        pieces.append("\n".join(missing_imports) + "\n")
    pieces.append("\n\n" + body.rstrip("\n") + "\n")

    # Ensure a clean separation if the existing file lacked a trailing newline.
    if existing and not existing.endswith("\n"):
        existing += "\n"
    new_content = existing + "".join(pieces) if existing else "".join(pieces)

    with open(file_path, "w", encoding="utf-8") as handle:
        handle.write(new_content)
