# Generated by Django 4.2.15 on 2024-08-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskPriorityOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option_type",
                    models.CharField(
                        blank=True,
                        choices=[("dm", "Default Mandatory"), ("do", "Default Optional"), ("cu", "Custom")],
                        default="do",
                        max_length=3,
                        verbose_name="Option Type",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Option Name")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this option deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Priority Option",
                "verbose_name_plural": "Task Priority Options",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatusOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option_type",
                    models.CharField(
                        blank=True,
                        choices=[("dm", "Default Mandatory"), ("do", "Default Optional"), ("cu", "Custom")],
                        default="do",
                        max_length=3,
                        verbose_name="Option Type",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Option Name")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this option deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Status Option",
                "verbose_name_plural": "Task Status Options",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("subdomain", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskStatusSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this selection deleted?", null=True)),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="example.taskstatusoption",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="example.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Status Selection",
                "verbose_name_plural": "Task Status Selections",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taskstatusoption",
            name="associated_tenants",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_selections",
                related_query_name="%(app_label)s_%(class)ss_selected",
                through="example.TaskStatusSelection",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskstatusoption",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TaskPrioritySelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this selection deleted?", null=True)),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="example.taskpriorityoption",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="example.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Priority Selection",
                "verbose_name_plural": "Task Priority Selections",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taskpriorityoption",
            name="associated_tenants",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_selections",
                related_query_name="%(app_label)s_%(class)ss_selected",
                through="example.TaskPrioritySelection",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskpriorityoption",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="example.taskpriorityoption",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="example.taskstatusoption",
                    ),
                ),
            ],
        ),
    ]
