# Generated by Django 5.1.2 on 2024-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TaskPriorityOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option_type",
                    models.CharField(
                        blank=True,
                        choices=[("dm", "Default Mandatory"), ("do", "Default Optional"), ("cu", "Custom")],
                        default="do",
                        max_length=3,
                        verbose_name="Option Type",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Option Name")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this option deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Priority Option",
                "verbose_name_plural": "Task Priority Options",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskPrioritySelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this selection deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Priority Selection",
                "verbose_name_plural": "Task Priority Selections",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatusOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option_type",
                    models.CharField(
                        blank=True,
                        choices=[("dm", "Default Mandatory"), ("do", "Default Optional"), ("cu", "Custom")],
                        default="do",
                        max_length=3,
                        verbose_name="Option Type",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Option Name")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this option deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Status Option",
                "verbose_name_plural": "Task Status Options",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatusSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(blank=True, help_text="When was this selection deleted?", null=True)),
            ],
            options={
                "verbose_name": "Task Status Selection",
                "verbose_name_plural": "Task Status Selections",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("subdomain", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
