# Generated by Django 5.1.2 on 2024-10-27 23:36

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("example", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="example.taskpriorityoption",
            ),
        ),
        migrations.AddField(
            model_name="taskpriorityselection",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.taskpriorityoption",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="example.taskstatusoption",
            ),
        ),
        migrations.AddField(
            model_name="taskstatusselection",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.taskstatusoption",
            ),
        ),
        migrations.AddField(
            model_name="taskstatusselection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskstatusoption",
            name="associated_tenants",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_selections",
                related_query_name="%(app_label)s_%(class)ss_selected",
                through="example.TaskStatusSelection",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskstatusoption",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskpriorityselection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskpriorityoption",
            name="associated_tenants",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_selections",
                related_query_name="%(app_label)s_%(class)ss_selected",
                through="example.TaskPrioritySelection",
                to="example.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskpriorityoption",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="example.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskstatusselection",
            constraint=models.UniqueConstraint(
                models.F("tenant"), models.F("option"), name="example_taskstatusselection_name_val"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskstatusoption",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="example_taskstatusoption_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskstatusoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("option_type", "cu"), ("tenant__isnull", False)),
                    models.Q(("option_type", "dm"), ("tenant__isnull", True)),
                    models.Q(("option_type", "do"), ("tenant__isnull", True)),
                    _connector="OR",
                ),
                name="example_taskstatusoption_tenant_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskpriorityselection",
            constraint=models.UniqueConstraint(
                models.F("tenant"), models.F("option"), name="example_taskpriorityselection_name_val"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskpriorityoption",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="example_taskpriorityoption_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskpriorityoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("option_type", "cu"), ("tenant__isnull", False)),
                    models.Q(("option_type", "dm"), ("tenant__isnull", True)),
                    models.Q(("option_type", "do"), ("tenant__isnull", True)),
                    _connector="OR",
                ),
                name="example_taskpriorityoption_tenant_check",
            ),
        ),
    ]
