# Generated by django-tenant-options on 2024-08-15 06:01

from django.db import migrations


class Migration(migrations.Migration):
    """Adds an auto-generated trigger for a django-tenant-options Selection model."""

    dependencies = [
        ("example", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    DROP TRIGGER IF EXISTS example_taskpriorityselection_tenant_check_142938904c;
    CREATE TRIGGER example_taskpriorityselection_tenant_check_142938904c
    BEFORE INSERT ON example_taskpriorityselection
    FOR EACH ROW
    WHEN NEW.tenant_id != (SELECT tenant_id FROM example_taskpriorityselection WHERE id = NEW.option_id)
    BEGIN
        SELECT RAISE(FAIL, 'Tenant mismatch between example_taskpriorityselection and the associated Option');
    END;
    """,
            reverse_sql="""DROP TRIGGER IF EXISTS example_taskpriorityselection_tenant_check_142938904c;""",
        ),
    ]
