# Generated by django-tenant-options on 2024-08-15 06:01

from django.db import migrations


class Migration(migrations.Migration):
    """Adds an auto-generated trigger for a django-tenant-options Selection model."""

    dependencies = [
        ('example', '0003_auto_trigger_taskpriorityselection'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    DROP TRIGGER IF EXISTS example_taskstatusselection_tenant_check_490fa5e2ab;
    CREATE TRIGGER example_taskstatusselection_tenant_check_490fa5e2ab
    BEFORE INSERT ON example_taskstatusselection
    FOR EACH ROW
    WHEN NEW.tenant_id != (SELECT tenant_id FROM example_taskstatusselection WHERE id = NEW.option_id)
    BEGIN
        SELECT RAISE(FAIL, 'Tenant mismatch between example_taskstatusselection and the associated Option');
    END;
    """,
            reverse_sql="""DROP TRIGGER IF EXISTS example_taskstatusselection_tenant_check_490fa5e2ab;""",
        ),
    ]
